apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lofar-download
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lofar-download
  template:
    metadata:
      labels:
        app: lofar-download
    spec:
      containers:
        - name: lofar-download
          image: microinfrastructure/adaptor-lofar-download
          env:
            - name: "DEBUG"
              value: "true"
            - name: "LOFARDOWNLOAD_SERVICE"
              value: "http://lobcder.process-project.eu:31888"
---
apiVersion: v1
kind: Service
metadata:
  name: lofar-download
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 31888
  selector:
    app: lofar-download